// Word list for the English Vocabulary Missile Game
// Based on the Israeli MoE English curriculum vocabulary for grades 4-5.
// band 1 = easier (levels 1-2), band 2 = harder (added from level 3)
const WORDS = [
  // ---- Colors (band 1) ----
  { en: "red", he: "אדום", topic: "colors", band: 1 },
  { en: "blue", he: "כחול", topic: "colors", band: 1 },
  { en: "green", he: "ירוק", topic: "colors", band: 1 },
  { en: "yellow", he: "צהוב", topic: "colors", band: 1 },
  { en: "black", he: "שחור", topic: "colors", band: 1 },
  { en: "white", he: "לבן", topic: "colors", band: 1 },
  { en: "orange", he: "כתום", topic: "colors", band: 1 },
  { en: "pink", he: "ורוד", topic: "colors", band: 1 },
  { en: "brown", he: "חום", topic: "colors", band: 1 },
  { en: "purple", he: "סגול", topic: "colors", band: 1 },
  { en: "gray", he: "אפור", topic: "colors", band: 1 },

  // ---- Animals (band 1) ----
  { en: "dog", he: "כלב", topic: "animals", band: 1 },
  { en: "cat", he: "חתול", topic: "animals", band: 1 },
  { en: "bird", he: "ציפור", topic: "animals", band: 1 },
  { en: "fish", he: "דג", topic: "animals", band: 1 },
  { en: "horse", he: "סוס", topic: "animals", band: 1 },
  { en: "cow", he: "פרה", topic: "animals", band: 1 },
  { en: "sheep", he: "כבשה", topic: "animals", band: 1 },
  { en: "duck", he: "ברווז", topic: "animals", band: 1 },
  { en: "rabbit", he: "ארנב", topic: "animals", band: 1 },
  { en: "mouse", he: "עכבר", topic: "animals", band: 1 },
  { en: "lion", he: "אריה", topic: "animals", band: 1 },
  { en: "elephant", he: "פיל", topic: "animals", band: 1 },
  { en: "monkey", he: "קוף", topic: "animals", band: 1 },
  { en: "snake", he: "נחש", topic: "animals", band: 1 },
  { en: "bear", he: "דוב", topic: "animals", band: 1 },
  { en: "tiger", he: "נמר", topic: "animals", band: 1 },
  { en: "frog", he: "צפרדע", topic: "animals", band: 1 },
  { en: "turtle", he: "צב", topic: "animals", band: 1 },
  // ---- Animals (band 2) ----
  { en: "butterfly", he: "פרפר", topic: "animals", band: 2 },
  { en: "spider", he: "עכביש", topic: "animals", band: 2 },
  { en: "ant", he: "נמלה", topic: "animals", band: 2 },
  { en: "bee", he: "דבורה", topic: "animals", band: 2 },
  { en: "wolf", he: "זאב", topic: "animals", band: 2 },
  { en: "fox", he: "שועל", topic: "animals", band: 2 },
  { en: "owl", he: "ינשוף", topic: "animals", band: 2 },
  { en: "camel", he: "גמל", topic: "animals", band: 2 },
  { en: "donkey", he: "חמור", topic: "animals", band: 2 },
  { en: "goat", he: "עז", topic: "animals", band: 2 },
  { en: "pig", he: "חזיר", topic: "animals", band: 2 },
  { en: "whale", he: "לווייתן", topic: "animals", band: 2 },
  { en: "shark", he: "כריש", topic: "animals", band: 2 },
  { en: "dolphin", he: "דולפין", topic: "animals", band: 2 },

  // ---- Family & people (band 1) ----
  { en: "mother", he: "אמא", topic: "family", band: 1 },
  { en: "father", he: "אבא", topic: "family", band: 1 },
  { en: "brother", he: "אח", topic: "family", band: 1 },
  { en: "sister", he: "אחות", topic: "family", band: 1 },
  { en: "baby", he: "תינוק", topic: "family", band: 1 },
  { en: "grandmother", he: "סבתא", topic: "family", band: 1 },
  { en: "grandfather", he: "סבא", topic: "family", band: 1 },
  { en: "family", he: "משפחה", topic: "family", band: 1 },
  { en: "uncle", he: "דוד", topic: "family", band: 1 },
  { en: "aunt", he: "דודה", topic: "family", band: 1 },
  { en: "boy", he: "ילד", topic: "family", band: 1 },
  { en: "girl", he: "ילדה", topic: "family", band: 1 },
  { en: "friend", he: "חבר", topic: "family", band: 1 },
  { en: "children", he: "ילדים", topic: "family", band: 1 },
  // ---- People (band 2) ----
  { en: "man", he: "איש", topic: "family", band: 2 },
  { en: "woman", he: "אישה", topic: "family", band: 2 },
  { en: "king", he: "מלך", topic: "family", band: 2 },
  { en: "queen", he: "מלכה", topic: "family", band: 2 },
  { en: "doctor", he: "רופא", topic: "family", band: 2 },
  { en: "policeman", he: "שוטר", topic: "family", band: 2 },
  { en: "driver", he: "נהג", topic: "family", band: 2 },
  { en: "farmer", he: "חקלאי", topic: "family", band: 2 },
  { en: "neighbor", he: "שכן", topic: "family", band: 2 },

  // ---- Body (band 1) ----
  { en: "head", he: "ראש", topic: "body", band: 1 },
  { en: "hand", he: "יד", topic: "body", band: 1 },
  { en: "leg", he: "רגל", topic: "body", band: 1 },
  { en: "eye", he: "עין", topic: "body", band: 1 },
  { en: "ear", he: "אוזן", topic: "body", band: 1 },
  { en: "nose", he: "אף", topic: "body", band: 1 },
  { en: "mouth", he: "פה", topic: "body", band: 1 },
  { en: "hair", he: "שיער", topic: "body", band: 1 },
  { en: "foot", he: "כף רגל", topic: "body", band: 1 },
  { en: "finger", he: "אצבע", topic: "body", band: 1 },
  { en: "tooth", he: "שן", topic: "body", band: 1 },
  { en: "face", he: "פנים", topic: "body", band: 1 },
  { en: "back", he: "גב", topic: "body", band: 1 },
  { en: "knee", he: "ברך", topic: "body", band: 2 },
  { en: "shoulder", he: "כתף", topic: "body", band: 2 },

  // ---- School (band 1) ----
  { en: "school", he: "בית ספר", topic: "school", band: 1 },
  { en: "teacher", he: "מורה", topic: "school", band: 1 },
  { en: "book", he: "ספר", topic: "school", band: 1 },
  { en: "pen", he: "עט", topic: "school", band: 1 },
  { en: "pencil", he: "עיפרון", topic: "school", band: 1 },
  { en: "bag", he: "תיק", topic: "school", band: 1 },
  { en: "notebook", he: "מחברת", topic: "school", band: 1 },
  { en: "eraser", he: "מחק", topic: "school", band: 1 },
  { en: "classroom", he: "כיתה", topic: "school", band: 1 },
  { en: "student", he: "תלמיד", topic: "school", band: 1 },
  { en: "homework", he: "שיעורי בית", topic: "school", band: 1 },
  { en: "lesson", he: "שיעור", topic: "school", band: 1 },
  { en: "board", he: "לוח", topic: "school", band: 2 },
  { en: "scissors", he: "מספריים", topic: "school", band: 2 },
  { en: "glue", he: "דבק", topic: "school", band: 2 },

  // ---- Food (band 1) ----
  { en: "apple", he: "תפוח", topic: "food", band: 1 },
  { en: "banana", he: "בננה", topic: "food", band: 1 },
  { en: "bread", he: "לחם", topic: "food", band: 1 },
  { en: "milk", he: "חלב", topic: "food", band: 1 },
  { en: "water", he: "מים", topic: "food", band: 1 },
  { en: "egg", he: "ביצה", topic: "food", band: 1 },
  { en: "cheese", he: "גבינה", topic: "food", band: 1 },
  { en: "cake", he: "עוגה", topic: "food", band: 1 },
  { en: "ice cream", he: "גלידה", topic: "food", band: 1 },
  { en: "juice", he: "מיץ", topic: "food", band: 1 },
  { en: "pizza", he: "פיצה", topic: "food", band: 1 },
  { en: "chocolate", he: "שוקולד", topic: "food", band: 1 },
  { en: "rice", he: "אורז", topic: "food", band: 1 },
  { en: "soup", he: "מרק", topic: "food", band: 1 },
  { en: "salad", he: "סלט", topic: "food", band: 1 },
  { en: "cookie", he: "עוגייה", topic: "food", band: 1 },
  { en: "candy", he: "ממתק", topic: "food", band: 1 },
  { en: "tomato", he: "עגבנייה", topic: "food", band: 1 },
  { en: "cucumber", he: "מלפפון", topic: "food", band: 1 },
  { en: "fruit", he: "פרי", topic: "food", band: 1 },
  // ---- Food (band 2) ----
  { en: "vegetables", he: "ירקות", topic: "food", band: 2 },
  { en: "meat", he: "בשר", topic: "food", band: 2 },
  { en: "butter", he: "חמאה", topic: "food", band: 2 },
  { en: "honey", he: "דבש", topic: "food", band: 2 },
  { en: "sugar", he: "סוכר", topic: "food", band: 2 },
  { en: "salt", he: "מלח", topic: "food", band: 2 },
  { en: "tea", he: "תה", topic: "food", band: 2 },
  { en: "coffee", he: "קפה", topic: "food", band: 2 },
  { en: "grapes", he: "ענבים", topic: "food", band: 2 },
  { en: "watermelon", he: "אבטיח", topic: "food", band: 2 },
  { en: "strawberry", he: "תות", topic: "food", band: 2 },
  { en: "lemon", he: "לימון", topic: "food", band: 2 },
  { en: "onion", he: "בצל", topic: "food", band: 2 },
  { en: "potato", he: "תפוח אדמה", topic: "food", band: 2 },
  { en: "corn", he: "תירס", topic: "food", band: 2 },
  { en: "breakfast", he: "ארוחת בוקר", topic: "food", band: 2 },
  { en: "lunch", he: "ארוחת צהריים", topic: "food", band: 2 },
  { en: "dinner", he: "ארוחת ערב", topic: "food", band: 2 },

  // ---- House (band 1) ----
  { en: "house", he: "בית", topic: "house", band: 1 },
  { en: "door", he: "דלת", topic: "house", band: 1 },
  { en: "window", he: "חלון", topic: "house", band: 1 },
  { en: "table", he: "שולחן", topic: "house", band: 1 },
  { en: "chair", he: "כיסא", topic: "house", band: 1 },
  { en: "bed", he: "מיטה", topic: "house", band: 1 },
  { en: "room", he: "חדר", topic: "house", band: 1 },
  { en: "kitchen", he: "מטבח", topic: "house", band: 1 },
  { en: "garden", he: "גינה", topic: "house", band: 1 },
  { en: "wall", he: "קיר", topic: "house", band: 1 },
  { en: "floor", he: "רצפה", topic: "house", band: 1 },
  { en: "roof", he: "גג", topic: "house", band: 1 },
  // ---- House (band 2) ----
  { en: "bathroom", he: "חדר אמבטיה", topic: "house", band: 2 },
  { en: "bedroom", he: "חדר שינה", topic: "house", band: 2 },
  { en: "living room", he: "סלון", topic: "house", band: 2 },
  { en: "stairs", he: "מדרגות", topic: "house", band: 2 },
  { en: "mirror", he: "מראה", topic: "house", band: 2 },
  { en: "lamp", he: "מנורה", topic: "house", band: 2 },
  { en: "cupboard", he: "ארון", topic: "house", band: 2 },
  { en: "fridge", he: "מקרר", topic: "house", band: 2 },
  { en: "towel", he: "מגבת", topic: "house", band: 2 },
  { en: "pillow", he: "כרית", topic: "house", band: 2 },
  { en: "blanket", he: "שמיכה", topic: "house", band: 2 },

  // ---- Clothes (band 1) ----
  { en: "shirt", he: "חולצה", topic: "clothes", band: 1 },
  { en: "pants", he: "מכנסיים", topic: "clothes", band: 1 },
  { en: "shoes", he: "נעליים", topic: "clothes", band: 1 },
  { en: "hat", he: "כובע", topic: "clothes", band: 1 },
  { en: "dress", he: "שמלה", topic: "clothes", band: 1 },
  { en: "socks", he: "גרביים", topic: "clothes", band: 1 },
  { en: "coat", he: "מעיל", topic: "clothes", band: 1 },
  { en: "skirt", he: "חצאית", topic: "clothes", band: 2 },
  { en: "sweater", he: "סוודר", topic: "clothes", band: 2 },
  { en: "pajamas", he: "פיג'מה", topic: "clothes", band: 2 },
  { en: "glasses", he: "משקפיים", topic: "clothes", band: 2 },
  { en: "umbrella", he: "מטרייה", topic: "clothes", band: 2 },

  // ---- Nature & weather (band 1) ----
  { en: "sun", he: "שמש", topic: "nature", band: 1 },
  { en: "moon", he: "ירח", topic: "nature", band: 1 },
  { en: "star", he: "כוכב", topic: "nature", band: 1 },
  { en: "sky", he: "שמיים", topic: "nature", band: 1 },
  { en: "rain", he: "גשם", topic: "nature", band: 1 },
  { en: "tree", he: "עץ", topic: "nature", band: 1 },
  { en: "flower", he: "פרח", topic: "nature", band: 1 },
  { en: "sea", he: "ים", topic: "nature", band: 1 },
  { en: "cloud", he: "ענן", topic: "nature", band: 1 },
  { en: "wind", he: "רוח", topic: "nature", band: 1 },
  { en: "snow", he: "שלג", topic: "nature", band: 1 },
  { en: "fire", he: "אש", topic: "nature", band: 1 },
  // ---- Nature (band 2) ----
  { en: "mountain", he: "הר", topic: "nature", band: 2 },
  { en: "river", he: "נהר", topic: "nature", band: 2 },
  { en: "forest", he: "יער", topic: "nature", band: 2 },
  { en: "desert", he: "מדבר", topic: "nature", band: 2 },
  { en: "island", he: "אי", topic: "nature", band: 2 },
  { en: "stone", he: "אבן", topic: "nature", band: 2 },
  { en: "sand", he: "חול", topic: "nature", band: 2 },
  { en: "grass", he: "דשא", topic: "nature", band: 2 },
  { en: "leaf", he: "עלה", topic: "nature", band: 2 },
  { en: "ice", he: "קרח", topic: "nature", band: 2 },
  { en: "weather", he: "מזג אוויר", topic: "nature", band: 2 },
  { en: "world", he: "עולם", topic: "nature", band: 2 },
  { en: "rainbow", he: "קשת בענן", topic: "nature", band: 2 },

  // ---- Time (band 2) ----
  { en: "day", he: "יום", topic: "time", band: 1 },
  { en: "night", he: "לילה", topic: "time", band: 1 },
  { en: "morning", he: "בוקר", topic: "time", band: 1 },
  { en: "evening", he: "ערב", topic: "time", band: 1 },
  { en: "week", he: "שבוע", topic: "time", band: 2 },
  { en: "month", he: "חודש", topic: "time", band: 2 },
  { en: "year", he: "שנה", topic: "time", band: 2 },
  { en: "today", he: "היום", topic: "time", band: 2 },
  { en: "tomorrow", he: "מחר", topic: "time", band: 2 },
  { en: "yesterday", he: "אתמול", topic: "time", band: 2 },
  { en: "hour", he: "שעה", topic: "time", band: 2 },
  { en: "minute", he: "דקה", topic: "time", band: 2 },
  { en: "clock", he: "שעון", topic: "time", band: 2 },
  { en: "birthday", he: "יום הולדת", topic: "time", band: 1 },
  { en: "holiday", he: "חג", topic: "time", band: 2 },
  { en: "summer", he: "קיץ", topic: "time", band: 2 },
  { en: "winter", he: "חורף", topic: "time", band: 2 },
  { en: "spring", he: "אביב", topic: "time", band: 2 },
  { en: "autumn", he: "סתיו", topic: "time", band: 2 },

  // ---- Places (band 2) ----
  { en: "city", he: "עיר", topic: "places", band: 2 },
  { en: "street", he: "רחוב", topic: "places", band: 2 },
  { en: "park", he: "פארק", topic: "places", band: 1 },
  { en: "zoo", he: "גן חיות", topic: "places", band: 1 },
  { en: "beach", he: "חוף", topic: "places", band: 2 },
  { en: "shop", he: "חנות", topic: "places", band: 2 },
  { en: "hospital", he: "בית חולים", topic: "places", band: 2 },
  { en: "library", he: "ספרייה", topic: "places", band: 2 },
  { en: "restaurant", he: "מסעדה", topic: "places", band: 2 },
  { en: "playground", he: "מגרש משחקים", topic: "places", band: 2 },
  { en: "farm", he: "חווה", topic: "places", band: 2 },
  { en: "bridge", he: "גשר", topic: "places", band: 2 },
  { en: "road", he: "כביש", topic: "places", band: 2 },
  { en: "village", he: "כפר", topic: "places", band: 2 },
  { en: "country", he: "מדינה", topic: "places", band: 2 },

  // ---- Transport (band 1) ----
  { en: "car", he: "מכונית", topic: "transport", band: 1 },
  { en: "bus", he: "אוטובוס", topic: "transport", band: 1 },
  { en: "train", he: "רכבת", topic: "transport", band: 1 },
  { en: "plane", he: "מטוס", topic: "transport", band: 1 },
  { en: "boat", he: "סירה", topic: "transport", band: 1 },
  { en: "bicycle", he: "אופניים", topic: "transport", band: 1 },
  { en: "truck", he: "משאית", topic: "transport", band: 2 },
  { en: "taxi", he: "מונית", topic: "transport", band: 2 },

  // ---- Things (band 1) ----
  { en: "ball", he: "כדור", topic: "things", band: 1 },
  { en: "game", he: "משחק", topic: "things", band: 1 },
  { en: "toy", he: "צעצוע", topic: "things", band: 1 },
  { en: "picture", he: "תמונה", topic: "things", band: 1 },
  { en: "money", he: "כסף", topic: "things", band: 1 },
  { en: "key", he: "מפתח", topic: "things", band: 1 },
  { en: "phone", he: "טלפון", topic: "things", band: 1 },
  { en: "computer", he: "מחשב", topic: "things", band: 1 },
  { en: "television", he: "טלוויזיה", topic: "things", band: 1 },
  { en: "music", he: "מוזיקה", topic: "things", band: 1 },
  { en: "song", he: "שיר", topic: "things", band: 1 },
  { en: "story", he: "סיפור", topic: "things", band: 1 },
  { en: "letter", he: "מכתב", topic: "things", band: 1 },
  { en: "present", he: "מתנה", topic: "things", band: 1 },
  { en: "party", he: "מסיבה", topic: "things", band: 1 },
  { en: "box", he: "קופסה", topic: "things", band: 1 },
  // ---- Things (band 2) ----
  { en: "question", he: "שאלה", topic: "things", band: 2 },
  { en: "answer", he: "תשובה", topic: "things", band: 2 },
  { en: "name", he: "שם", topic: "things", band: 2 },
  { en: "word", he: "מילה", topic: "things", band: 2 },
  { en: "sentence", he: "משפט", topic: "things", band: 2 },
  { en: "page", he: "עמוד", topic: "things", band: 2 },
  { en: "newspaper", he: "עיתון", topic: "things", band: 2 },
  { en: "movie", he: "סרט", topic: "things", band: 2 },
  { en: "team", he: "קבוצה", topic: "things", band: 2 },
  { en: "prize", he: "פרס", topic: "things", band: 2 },

  // ---- Verbs (band 1) ----
  { en: "eat", he: "לאכול", topic: "verbs", band: 1 },
  { en: "drink", he: "לשתות", topic: "verbs", band: 1 },
  { en: "sleep", he: "לישון", topic: "verbs", band: 1 },
  { en: "play", he: "לשחק", topic: "verbs", band: 1 },
  { en: "read", he: "לקרוא", topic: "verbs", band: 1 },
  { en: "write", he: "לכתוב", topic: "verbs", band: 1 },
  { en: "run", he: "לרוץ", topic: "verbs", band: 1 },
  { en: "jump", he: "לקפוץ", topic: "verbs", band: 1 },
  { en: "sing", he: "לשיר", topic: "verbs", band: 1 },
  { en: "dance", he: "לרקוד", topic: "verbs", band: 1 },
  { en: "swim", he: "לשחות", topic: "verbs", band: 1 },
  { en: "see", he: "לראות", topic: "verbs", band: 1 },
  { en: "hear", he: "לשמוע", topic: "verbs", band: 1 },
  { en: "speak", he: "לדבר", topic: "verbs", band: 1 },
  { en: "love", he: "לאהוב", topic: "verbs", band: 1 },
  { en: "want", he: "לרצות", topic: "verbs", band: 1 },
  { en: "open", he: "לפתוח", topic: "verbs", band: 1 },
  { en: "close", he: "לסגור", topic: "verbs", band: 1 },
  { en: "give", he: "לתת", topic: "verbs", band: 1 },
  { en: "take", he: "לקחת", topic: "verbs", band: 1 },
  { en: "come", he: "לבוא", topic: "verbs", band: 1 },
  { en: "go", he: "ללכת", topic: "verbs", band: 1 },
  { en: "sit", he: "לשבת", topic: "verbs", band: 1 },
  { en: "stand", he: "לעמוד", topic: "verbs", band: 1 },
  // ---- Verbs (band 2) ----
  { en: "help", he: "לעזור", topic: "verbs", band: 2 },
  { en: "learn", he: "ללמוד", topic: "verbs", band: 2 },
  { en: "teach", he: "ללמד", topic: "verbs", band: 2 },
  { en: "buy", he: "לקנות", topic: "verbs", band: 2 },
  { en: "sell", he: "למכור", topic: "verbs", band: 2 },
  { en: "fly", he: "לעוף", topic: "verbs", band: 2 },
  { en: "drive", he: "לנהוג", topic: "verbs", band: 2 },
  { en: "wash", he: "לרחוץ", topic: "verbs", band: 2 },
  { en: "listen", he: "להקשיב", topic: "verbs", band: 2 },
  { en: "look", he: "להסתכל", topic: "verbs", band: 2 },
  { en: "find", he: "למצוא", topic: "verbs", band: 2 },
  { en: "lose", he: "לאבד", topic: "verbs", band: 2 },
  { en: "win", he: "לנצח", topic: "verbs", band: 2 },
  { en: "throw", he: "לזרוק", topic: "verbs", band: 2 },
  { en: "catch", he: "לתפוס", topic: "verbs", band: 2 },
  { en: "ride", he: "לרכוב", topic: "verbs", band: 2 },
  { en: "draw", he: "לצייר", topic: "verbs", band: 2 },
  { en: "ask", he: "לשאול", topic: "verbs", band: 2 },
  { en: "know", he: "לדעת", topic: "verbs", band: 2 },
  { en: "think", he: "לחשוב", topic: "verbs", band: 2 },
  { en: "remember", he: "לזכור", topic: "verbs", band: 2 },
  { en: "forget", he: "לשכוח", topic: "verbs", band: 2 },
  { en: "wait", he: "לחכות", topic: "verbs", band: 2 },
  { en: "start", he: "להתחיל", topic: "verbs", band: 2 },
  { en: "finish", he: "לסיים", topic: "verbs", band: 2 },
  { en: "live", he: "לגור", topic: "verbs", band: 2 },
  { en: "work", he: "לעבוד", topic: "verbs", band: 2 },
  { en: "visit", he: "לבקר", topic: "verbs", band: 2 },
  { en: "travel", he: "לטייל", topic: "verbs", band: 2 },
  { en: "wear", he: "ללבוש", topic: "verbs", band: 2 },
  { en: "bring", he: "להביא", topic: "verbs", band: 2 },
  { en: "send", he: "לשלוח", topic: "verbs", band: 2 },
  { en: "meet", he: "לפגוש", topic: "verbs", band: 2 },
  { en: "smile", he: "לחייך", topic: "verbs", band: 2 },
  { en: "cry", he: "לבכות", topic: "verbs", band: 2 },
  { en: "laugh", he: "לצחוק", topic: "verbs", band: 2 },

  // ---- Adjectives (band 1) ----
  { en: "big", he: "גדול", topic: "adjectives", band: 1 },
  { en: "small", he: "קטן", topic: "adjectives", band: 1 },
  { en: "happy", he: "שמח", topic: "adjectives", band: 1 },
  { en: "sad", he: "עצוב", topic: "adjectives", band: 1 },
  { en: "good", he: "טוב", topic: "adjectives", band: 1 },
  { en: "bad", he: "רע", topic: "adjectives", band: 1 },
  { en: "new", he: "חדש", topic: "adjectives", band: 1 },
  { en: "old", he: "ישן", topic: "adjectives", band: 1 },
  { en: "fast", he: "מהיר", topic: "adjectives", band: 1 },
  { en: "slow", he: "איטי", topic: "adjectives", band: 1 },
  { en: "beautiful", he: "יפה", topic: "adjectives", band: 1 },
  { en: "tall", he: "גבוה", topic: "adjectives", band: 1 },
  { en: "short", he: "נמוך", topic: "adjectives", band: 1 },
  { en: "clean", he: "נקי", topic: "adjectives", band: 1 },
  { en: "dirty", he: "מלוכלך", topic: "adjectives", band: 1 },
  { en: "strong", he: "חזק", topic: "adjectives", band: 1 },
  { en: "hot", he: "חם", topic: "adjectives", band: 1 },
  { en: "cold", he: "קר", topic: "adjectives", band: 1 },
  // ---- Adjectives (band 2) ----
  { en: "angry", he: "כועס", topic: "adjectives", band: 2 },
  { en: "tired", he: "עייף", topic: "adjectives", band: 2 },
  { en: "hungry", he: "רעב", topic: "adjectives", band: 2 },
  { en: "thirsty", he: "צמא", topic: "adjectives", band: 2 },
  { en: "scared", he: "מפוחד", topic: "adjectives", band: 2 },
  { en: "funny", he: "מצחיק", topic: "adjectives", band: 2 },
  { en: "easy", he: "קל", topic: "adjectives", band: 2 },
  { en: "difficult", he: "קשה", topic: "adjectives", band: 2 },
  { en: "expensive", he: "יקר", topic: "adjectives", band: 2 },
  { en: "cheap", he: "זול", topic: "adjectives", band: 2 },
  { en: "full", he: "מלא", topic: "adjectives", band: 2 },
  { en: "empty", he: "ריק", topic: "adjectives", band: 2 },
  { en: "quiet", he: "שקט", topic: "adjectives", band: 2 },
  { en: "dangerous", he: "מסוכן", topic: "adjectives", band: 2 },
  { en: "important", he: "חשוב", topic: "adjectives", band: 2 },
  { en: "interesting", he: "מעניין", topic: "adjectives", band: 2 },
  { en: "boring", he: "משעמם", topic: "adjectives", band: 2 },
  { en: "wet", he: "רטוב", topic: "adjectives", band: 2 },
  { en: "dry", he: "יבש", topic: "adjectives", band: 2 },
  { en: "heavy", he: "כבד", topic: "adjectives", band: 2 },
  { en: "rich", he: "עשיר", topic: "adjectives", band: 2 },
  { en: "poor", he: "עני", topic: "adjectives", band: 2 },
  { en: "sick", he: "חולה", topic: "adjectives", band: 2 },
  { en: "healthy", he: "בריא", topic: "adjectives", band: 2 },
  { en: "careful", he: "זהיר", topic: "adjectives", band: 2 },
  { en: "special", he: "מיוחד", topic: "adjectives", band: 2 },
  { en: "different", he: "שונה", topic: "adjectives", band: 2 },
  { en: "ready", he: "מוכן", topic: "adjectives", band: 2 },
  { en: "near", he: "קרוב", topic: "adjectives", band: 2 },
  { en: "far", he: "רחוק", topic: "adjectives", band: 2 },
  { en: "early", he: "מוקדם", topic: "adjectives", band: 2 },
  { en: "late", he: "מאוחר", topic: "adjectives", band: 2 },

  // ---- Verbs (band 3 — advanced) ----
  { en: "believe", he: "להאמין", topic: "verbs", band: 3 },
  { en: "decide", he: "להחליט", topic: "verbs", band: 3 },
  { en: "promise", he: "להבטיח", topic: "verbs", band: 3 },
  { en: "choose", he: "לבחור", topic: "verbs", band: 3 },
  { en: "build", he: "לבנות", topic: "verbs", band: 3 },
  { en: "break", he: "לשבור", topic: "verbs", band: 3 },
  { en: "change", he: "לשנות", topic: "verbs", band: 3 },
  { en: "dream", he: "לחלום", topic: "verbs", band: 3 },
  { en: "explain", he: "להסביר", topic: "verbs", band: 3 },
  { en: "feel", he: "להרגיש", topic: "verbs", band: 3 },
  { en: "follow", he: "לעקוב", topic: "verbs", band: 3 },
  { en: "grow", he: "לגדול", topic: "verbs", band: 3 },
  { en: "happen", he: "לקרות", topic: "verbs", band: 3 },
  { en: "hate", he: "לשנוא", topic: "verbs", band: 3 },
  { en: "hope", he: "לקוות", topic: "verbs", band: 3 },
  { en: "invite", he: "להזמין", topic: "verbs", band: 3 },
  { en: "join", he: "להצטרף", topic: "verbs", band: 3 },
  { en: "keep", he: "לשמור", topic: "verbs", band: 3 },
  { en: "kick", he: "לבעוט", topic: "verbs", band: 3 },
  { en: "leave", he: "לעזוב", topic: "verbs", band: 3 },
  { en: "move", he: "לזוז", topic: "verbs", band: 3 },
  { en: "pay", he: "לשלם", topic: "verbs", band: 3 },
  { en: "plan", he: "לתכנן", topic: "verbs", band: 3 },
  { en: "practice", he: "להתאמן", topic: "verbs", band: 3 },
  { en: "prepare", he: "להכין", topic: "verbs", band: 3 },
  { en: "pull", he: "למשוך", topic: "verbs", band: 3 },
  { en: "push", he: "לדחוף", topic: "verbs", band: 3 },
  { en: "put", he: "לשים", topic: "verbs", band: 3 },
  { en: "reach", he: "להגיע", topic: "verbs", band: 3 },
  { en: "rest", he: "לנוח", topic: "verbs", band: 3 },
  { en: "return", he: "לחזור", topic: "verbs", band: 3 },
  { en: "save", he: "להציל", topic: "verbs", band: 3 },
  { en: "say", he: "להגיד", topic: "verbs", band: 3 },
  { en: "tell", he: "לספר", topic: "verbs", band: 3 },
  { en: "taste", he: "לטעום", topic: "verbs", band: 3 },
  { en: "touch", he: "לגעת", topic: "verbs", band: 3 },
  { en: "try", he: "לנסות", topic: "verbs", band: 3 },
  { en: "understand", he: "להבין", topic: "verbs", band: 3 },
  { en: "use", he: "להשתמש", topic: "verbs", band: 3 },
  { en: "worry", he: "לדאוג", topic: "verbs", band: 3 },
  { en: "wake up", he: "להתעורר", topic: "verbs", band: 3 },
  { en: "fall", he: "ליפול", topic: "verbs", band: 3 },
  { en: "hold", he: "להחזיק", topic: "verbs", band: 3 },
  { en: "hide", he: "להתחבא", topic: "verbs", band: 3 },
  { en: "guess", he: "לנחש", topic: "verbs", band: 3 },
  { en: "count", he: "לספור", topic: "verbs", band: 3 },
  { en: "shout", he: "לצעוק", topic: "verbs", band: 3 },

  // ---- Adjectives (band 3 — advanced) ----
  { en: "brave", he: "אמיץ", topic: "adjectives", band: 3 },
  { en: "proud", he: "גאה", topic: "adjectives", band: 3 },
  { en: "polite", he: "מנומס", topic: "adjectives", band: 3 },
  { en: "rude", he: "חצוף", topic: "adjectives", band: 3 },
  { en: "lazy", he: "עצלן", topic: "adjectives", band: 3 },
  { en: "busy", he: "עסוק", topic: "adjectives", band: 3 },
  { en: "famous", he: "מפורסם", topic: "adjectives", band: 3 },
  { en: "lucky", he: "בר מזל", topic: "adjectives", band: 3 },
  { en: "surprised", he: "מופתע", topic: "adjectives", band: 3 },
  { en: "excited", he: "נרגש", topic: "adjectives", band: 3 },
  { en: "curious", he: "סקרן", topic: "adjectives", band: 3 },
  { en: "friendly", he: "ידידותי", topic: "adjectives", band: 3 },
  { en: "kind", he: "אדיב", topic: "adjectives", band: 3 },
  { en: "wild", he: "פראי", topic: "adjectives", band: 3 },
  { en: "calm", he: "רגוע", topic: "adjectives", band: 3 },
  { en: "noisy", he: "רועש", topic: "adjectives", band: 3 },
  { en: "dark", he: "חשוך", topic: "adjectives", band: 3 },
  { en: "deep", he: "עמוק", topic: "adjectives", band: 3 },
  { en: "wide", he: "רחב", topic: "adjectives", band: 3 },
  { en: "narrow", he: "צר", topic: "adjectives", band: 3 },
  { en: "sharp", he: "חד", topic: "adjectives", band: 3 },
  { en: "soft", he: "רך", topic: "adjectives", band: 3 },
  { en: "comfortable", he: "נוח", topic: "adjectives", band: 3 },
  { en: "terrible", he: "נורא", topic: "adjectives", band: 3 },
  { en: "wonderful", he: "נפלא", topic: "adjectives", band: 3 },
  { en: "safe", he: "בטוח", topic: "adjectives", band: 3 },
  { en: "real", he: "אמיתי", topic: "adjectives", band: 3 },

  // ---- Nouns (band 3 — advanced) ----
  { en: "adventure", he: "הרפתקה", topic: "things", band: 3 },
  { en: "idea", he: "רעיון", topic: "things", band: 3 },
  { en: "secret", he: "סוד", topic: "things", band: 3 },
  { en: "joke", he: "בדיחה", topic: "things", band: 3 },
  { en: "mistake", he: "טעות", topic: "things", band: 3 },
  { en: "problem", he: "בעיה", topic: "things", band: 3 },
  { en: "language", he: "שפה", topic: "things", band: 3 },
  { en: "machine", he: "מכונה", topic: "things", band: 3 },
  { en: "map", he: "מפה", topic: "things", band: 3 },
  { en: "medicine", he: "תרופה", topic: "things", band: 3 },
  { en: "message", he: "הודעה", topic: "things", band: 3 },
  { en: "news", he: "חדשות", topic: "things", band: 3 },
  { en: "price", he: "מחיר", topic: "things", band: 3 },
  { en: "sport", he: "ספורט", topic: "things", band: 3 },
  { en: "magic", he: "קסם", topic: "things", band: 3 },
  { en: "hero", he: "גיבור", topic: "family", band: 3 },
  { en: "soldier", he: "חייל", topic: "family", band: 3 },
  { en: "thief", he: "גנב", topic: "family", band: 3 },
  { en: "prince", he: "נסיך", topic: "family", band: 3 },
  { en: "princess", he: "נסיכה", topic: "family", band: 3 },
  { en: "enemy", he: "אויב", topic: "family", band: 3 },
  { en: "person", he: "אדם", topic: "family", band: 3 },
  { en: "air", he: "אוויר", topic: "nature", band: 3 },
  { en: "ground", he: "אדמה", topic: "nature", band: 3 },
  { en: "ocean", he: "אוקיינוס", topic: "nature", band: 3 },
  { en: "space", he: "חלל", topic: "nature", band: 3 },
  { en: "field", he: "שדה", topic: "nature", band: 3 },
  { en: "smoke", he: "עשן", topic: "nature", band: 3 },
  { en: "danger", he: "סכנה", topic: "things", band: 3 },
  { en: "voice", he: "קול", topic: "body", band: 3 },
  { en: "brain", he: "מוח", topic: "body", band: 3 },
  { en: "bone", he: "עצם", topic: "body", band: 3 },
  { en: "pain", he: "כאב", topic: "body", band: 3 },
  { en: "town", he: "עיירה", topic: "places", band: 3 },
  { en: "market", he: "שוק", topic: "places", band: 3 },
  { en: "war", he: "מלחמה", topic: "things", band: 3 },
  { en: "peace", he: "שלום", topic: "things", band: 3 },
  { en: "truth", he: "אמת", topic: "things", band: 3 },
  { en: "luck", he: "מזל", topic: "things", band: 3 },
  { en: "future", he: "עתיד", topic: "time", band: 3 },
  { en: "past", he: "עבר", topic: "time", band: 3 },
  { en: "memory", he: "זיכרון", topic: "things", band: 3 },
  { en: "wing", he: "כנף", topic: "animals", band: 3 },
  { en: "winner", he: "מנצח", topic: "family", band: 3 }
];
